'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace scripts

    Partial Public Class Alliances

        '''<summary>
        '''Form3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Form3 As Global.System.Web.UI.HtmlControls.HtmlForm

        '''<summary>
        '''Topinfobar1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Topinfobar1 As Global.sklone.TopInfoBar

        '''<summary>
        '''lblRulerName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblRulerName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblError control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblError As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblSuccess control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSuccess As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblCurrentAlliance control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCurrentAlliance As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''pnlAllianceInfo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlAllianceInfo As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''aInfo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents aInfo As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''aSectors control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents aSectors As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''aForums control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents aForums As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''pnlSL control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlSL As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''pnlJoin control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlJoin As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''txtAllianceName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAllianceName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtAlliancePassword control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAlliancePassword As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cmdJoin control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdJoin As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''pnlLeave control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlLeave As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''cmdLeave control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdLeave As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''pnlCreate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlCreate As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''txtCreateName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCreateName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtCreatePassword control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCreatePassword As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cmdCreate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdCreate As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''pnlAccess control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlAccess As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''txtAccessName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAccessName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cmdAccess control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdAccess As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''tblAlliances control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblAlliances As Global.System.Web.UI.WebControls.Table

        '''<summary>
        '''BottomInfoBar1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents BottomInfoBar1 As Global.SKlone.BottomInfoBar
    End Class
End Namespace
