'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace scripts

    Partial Public Class AllianceForumsThread

        '''<summary>
        '''lblLand control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblLand As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''Form1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Form1 As Global.System.Web.UI.HtmlControls.HtmlForm

        '''<summary>
        '''Topinfobar1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Topinfobar1 As Global.sklone.TopInfoBar

        '''<summary>
        '''pnlForums control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlForums As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblAlliance control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAlliance As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblAL control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAL As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''tblMessages control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblMessages As Global.System.Web.UI.WebControls.Table

        '''<summary>
        '''cmdDeletePosts control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdDeletePosts As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''txtMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMessage As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cmdReply control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdReply As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''pnlPosted control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlPosted As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''pnlBadThread control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlBadThread As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''pnlNoAlliance control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlNoAlliance As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''pnlDeleted control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlDeleted As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''aReturn control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents aReturn As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''BottomInfoBar1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents BottomInfoBar1 As Global.SKlone.BottomInfoBar
    End Class
End Namespace
