'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class KingdomChooser

    '''<summary>
    '''txtGalaxy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGalaxy As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSector control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSector As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cmdChangeSector control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdChangeSector As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''pnlAlliance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAlliance As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblAlliance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAlliance As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlAllianceRelation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAllianceRelation As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblAllianceRelation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAllianceRelation As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlExternalRelation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlExternalRelation As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblExternalRelation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExternalRelation As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboKingdoms control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboKingdoms As Global.System.Web.UI.WebControls.DropDownList
End Class
