CREATE TABLE [dbo].[Kingdoms] (
    [kdID]               INT            NOT NULL,
    [Name]               NVARCHAR (24)  NOT NULL,
    [RulerName]          NVARCHAR (24)  NOT NULL,
    [Population]         BIGINT         CONSTRAINT [DF_Kingdoms_Population] DEFAULT (2250) NOT NULL,
    [Money]              BIGINT         CONSTRAINT [DF_Kingdoms_Money] DEFAULT (175000) NOT NULL,
    [Power]              BIGINT         CONSTRAINT [DF_Kingdoms_Power] DEFAULT (500) NOT NULL,
    [RaceType]           TINYINT        NOT NULL,
    [PlanetType]         TINYINT        NOT NULL,
    [Probes]             INT            CONSTRAINT [DF_Kingdoms_Probes] DEFAULT (0) NOT NULL,
    [ProbeTurns]         TINYINT        CONSTRAINT [DF_Kingdoms_ProbeTurns] DEFAULT (10) NOT NULL,
    [MA]                 TINYINT        CONSTRAINT [DF_Kingdoms_MA] DEFAULT (0) NOT NULL,
    [X]                  TINYINT        CONSTRAINT [DF_Kingdoms_X] DEFAULT (round((rand() * 9),0) + 1) NOT NULL,
    [Y]                  TINYINT        CONSTRAINT [DF_Kingdoms_Y] DEFAULT (round((rand() * 9),0) + 1) NOT NULL,
    [SectorID]           INT            NULL,
    [Vote]               INT            NULL,
    [LastAttacker]       INT            NULL,
    [Attacks]            INT            CONSTRAINT [DF_Kingdoms_Attacks] DEFAULT (0) NOT NULL,
    [TroubleMode]        BIT            CONSTRAINT [DF_Kingdoms_TroubleMode] DEFAULT (0) NOT NULL,
    [Rank]               INT            CONSTRAINT [DF_Kingdoms_Rank] DEFAULT (0) NOT NULL,
    [Wins]               INT            CONSTRAINT [DF_Kingdoms_Wins] DEFAULT (0) NOT NULL,
    [Losses]             INT            CONSTRAINT [DF_Kingdoms_Losses] DEFAULT (0) NOT NULL,
    [Income]             INT            CONSTRAINT [DF_Kingdoms_Income] DEFAULT (0) NOT NULL,
    [PowerChange]        BIGINT         CONSTRAINT [DF_Kingdoms_PowerChange] DEFAULT (0) NOT NULL,
    [ShieldsPowerChange] BIGINT         CONSTRAINT [DF_Kingdoms_ShieldsPower] DEFAULT (0) NOT NULL,
    [PopulationChange]   INT            CONSTRAINT [DF_Kingdoms_PopulationChange] DEFAULT (0) NOT NULL,
    [Networth]           BIGINT         CONSTRAINT [DF_Kingdoms_Networth] DEFAULT (0) NOT NULL,
    [SectorOrder]        TINYINT        CONSTRAINT [DF_Kingdoms_SectorOrder] DEFAULT (0) NOT NULL,
    [Avatar]             NVARCHAR (200) NULL,
    [NetworthChange]     BIGINT         NULL,
    [FamilyID]           INT            NULL,
    CONSTRAINT [PK_kingdoms] PRIMARY KEY CLUSTERED ([kdID] ASC)
);

