CREATE TABLE [dbo].[UnitsTraining] (
    [kdID]        INT     NOT NULL,
    [UnitType]    TINYINT NOT NULL,
    [Complete]    INT     CONSTRAINT [DF_UnitsTraining_Complete] DEFAULT (0) NOT NULL,
    [Training0]   INT     CONSTRAINT [DF_UnitsTraining_Training0] DEFAULT (0) NOT NULL,
    [Training1]   INT     CONSTRAINT [DF_UnitsTraining_Training1] DEFAULT (0) NOT NULL,
    [Training2]   INT     CONSTRAINT [DF_UnitsTraining_Training2] DEFAULT (0) NOT NULL,
    [Training3]   INT     CONSTRAINT [DF_UnitsTraining_Training3] DEFAULT (0) NOT NULL,
    [Training4]   INT     CONSTRAINT [DF_UnitsTraining_Training4] DEFAULT (0) NOT NULL,
    [Training5]   INT     CONSTRAINT [DF_UnitsTraining_Training5] DEFAULT (0) NOT NULL,
    [Training6]   INT     CONSTRAINT [DF_UnitsTraining_Training6] DEFAULT (0) NOT NULL,
    [Training7]   INT     CONSTRAINT [DF_UnitsTraining_Training7] DEFAULT (0) NOT NULL,
    [Training8]   INT     CONSTRAINT [DF_UnitsTraining_Training8] DEFAULT (0) NOT NULL,
    [Training9]   INT     CONSTRAINT [DF_UnitsTraining_Training9] DEFAULT (0) NOT NULL,
    [Training10]  INT     CONSTRAINT [DF_UnitsTraining_Training10] DEFAULT (0) NOT NULL,
    [Training11]  INT     CONSTRAINT [DF_UnitsTraining_Training11] DEFAULT (0) NOT NULL,
    [Training12]  INT     CONSTRAINT [DF_UnitsTraining_Training12] DEFAULT (0) NOT NULL,
    [Training13]  INT     CONSTRAINT [DF_UnitsTraining_Training13] DEFAULT (0) NOT NULL,
    [Training14]  INT     CONSTRAINT [DF_UnitsTraining_Training14] DEFAULT (0) NOT NULL,
    [Training15]  INT     CONSTRAINT [DF_UnitsTraining_Training15] DEFAULT (0) NOT NULL,
    [Training16]  INT     CONSTRAINT [DF_UnitsTraining_Training16] DEFAULT (0) NOT NULL,
    [Training17]  INT     CONSTRAINT [DF_UnitsTraining_Training17] DEFAULT (0) NOT NULL,
    [Training18]  INT     CONSTRAINT [DF_UnitsTraining_Training18] DEFAULT (0) NOT NULL,
    [Training19]  INT     CONSTRAINT [DF_UnitsTraining_Training19] DEFAULT (0) NOT NULL,
    [Training20]  INT     CONSTRAINT [DF_UnitsTraining_Training20] DEFAULT (0) NOT NULL,
    [Training21]  INT     CONSTRAINT [DF_UnitsTraining_Training21] DEFAULT (0) NOT NULL,
    [Training22]  INT     CONSTRAINT [DF_UnitsTraining_Training22] DEFAULT (0) NOT NULL,
    [Training23]  INT     CONSTRAINT [DF_UnitsTraining_Training23] DEFAULT (0) NOT NULL,
    [UnitTypeOut] INT     NULL
);

